// <auto-generated />
using System;
using BachelorsPhSalesProcessor.Infrastructure.BrbRaw;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BachelorsPhSalesProcessor.Migrations.BrbRawDb
{
    [DbContext(typeof(BrbRawDbContext))]
    partial class BrbRawDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BachelorsPhSalesProcessor.DbSet.BrbRaw.SalesRaw.SalesRawDbSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AcceptanceProgress")
                        .HasColumnType("float")
                        .HasColumnName("acceptanceprogress");

                    b.Property<string>("Acct_Receivables_Rep_Entity_Flag")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar")
                        .HasColumnName("acct_receivables_rep_entity_flag");

                    b.Property<string>("Acct_Receivables_Rep_Flag")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar")
                        .HasColumnName("acct_receivables_rep_flag");

                    b.Property<double>("BrokerIncentive")
                        .HasColumnType("float")
                        .HasColumnName("brokerincentive");

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar")
                        .HasColumnName("buyername");

                    b.Property<double>("CommisionPercentage")
                        .HasColumnType("float")
                        .HasColumnName("commisionpercentage");

                    b.Property<double>("CommisionTotalAmount")
                        .HasColumnType("float")
                        .HasColumnName("commisiontotalamount");

                    b.Property<double>("CommisionableTcp")
                        .HasColumnType("float")
                        .HasColumnName("commisionabletcp");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("create_date");

                    b.Property<string>("Create_User")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("create_user");

                    b.Property<string>("Delete_Flag")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar")
                        .HasColumnName("delete_flag");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("details");

                    b.Property<int?>("Prprty_Id")
                        .HasColumnType("int")
                        .HasColumnName("prprty_id");

                    b.Property<string>("Public_Id")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("public_id");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remarks");

                    b.Property<string>("ReservationDate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar")
                        .HasColumnName("reservationdate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar")
                        .HasColumnName("status");

                    b.Property<double>("TotalContractPrice")
                        .HasColumnType("float")
                        .HasColumnName("totalcontractprice");

                    b.Property<DateTime>("Update_Date")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("update_date");

                    b.Property<string>("Update_User")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("update_user");

                    b.HasKey("Id");

                    b.ToTable("[b'brb_raw'].[sales]", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
